version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: english-assistant-db
    environment:
      POSTGRES_DB: english_assistant
      POSTGRES_USER: english_assistant_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/initial_data.sql:/docker-entrypoint-initdb.d/02-data.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U english_assistant_user -d english_assistant"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    container_name: english-assistant-api
    environment:
      - DATABASE_URL=postgresql://english_assistant_user:${DB_PASSWORD:-secure_password}@database:5432/english_assistant
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DEBUG=false
      - LOG_LEVEL=INFO
      - MODELS_CACHE_DIR=/app/models_cache
      - HF_HOME=/app/models_cache
    volumes:
      - models_cache:/app/models_cache
      - app_logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    container_name: english-assistant-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  models_cache:
    driver: local
  app_logs:
    driver: local

networks:
  default:
    name: english-assistant-network